"""changes

Revision ID: 03e8304e0a6d
Revises: fc1b561caf4d
Create Date: 2025-08-09 13:12:24.967428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03e8304e0a6d"
down_revision: Union[str, Sequence[str], None] = "fc1b561caf4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("filename", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "filename")
    # ### end Alembic commands ###
