"""add cascade delete

Revision ID: 4bb866c11099
Revises: c43c76a98651
Create Date: 2025-08-11 03:25:43.222426

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4bb866c11099"
down_revision: Union[str, Sequence[str], None] = "c43c76a98651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("chunks_embedding_idx"),
        table_name="chunks",
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_constraint(
        op.f("history_file_association_history_id_fkey"),
        "history_file_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("history_file_association_file_id_fkey"),
        "history_file_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "history_file_association",
        "history_meta",
        ["history_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "history_file_association",
        "file_meta",
        ["file_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("request_chunk_association_request_id_fkey"),
        "request_chunk_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("request_chunk_association_chunk_id_fkey"),
        "request_chunk_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "request_chunk_association",
        "chunks",
        ["chunk_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "request_chunk_association",
        "generation_requests",
        ["request_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "request_chunk_association", type_="foreignkey")
    op.drop_constraint(None, "request_chunk_association", type_="foreignkey")
    op.create_foreign_key(
        op.f("request_chunk_association_chunk_id_fkey"),
        "request_chunk_association",
        "chunks",
        ["chunk_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("request_chunk_association_request_id_fkey"),
        "request_chunk_association",
        "generation_requests",
        ["request_id"],
        ["id"],
    )
    op.drop_constraint(None, "history_file_association", type_="foreignkey")
    op.drop_constraint(None, "history_file_association", type_="foreignkey")
    op.create_foreign_key(
        op.f("history_file_association_file_id_fkey"),
        "history_file_association",
        "file_meta",
        ["file_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("history_file_association_history_id_fkey"),
        "history_file_association",
        "history_meta",
        ["history_id"],
        ["id"],
    )
    op.create_index(
        op.f("chunks_embedding_idx"),
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    # ### end Alembic commands ###
