"""Add request_id to messages

Revision ID: 58f50f9ef1b2
Revises: 2bff183dab40
Create Date: 2025-07-31 00:18:31.872547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58f50f9ef1b2"
down_revision: Union[str, Sequence[str], None] = "2bff183dab40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("chunks_embedding_idx"),
        table_name="chunks",
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.add_column("messages", sa.Column("request_id", sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "request_id")
    op.create_index(
        op.f("chunks_embedding_idx"),
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    # ### end Alembic commands ###
