"""Refactor relations

Revision ID: d3b2e0ad0b7a
Revises: a770a817fe49
Create Date: 2025-07-28 18:37:29.215557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3b2e0ad0b7a"
down_revision: Union[str, Sequence[str], None] = "a770a817fe49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_chunk_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_chunk_association",
        sa.Column("message_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("chunk_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("message_chunk_association_chunk_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("message_chunk_association_message_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "message_id", "chunk_id", name=op.f("message_chunk_association_pkey")
        ),
    )
    # ### end Alembic commands ###
