"""changes

Revision ID: e24ca79dd0e6
Revises: b1b3cc050712
Create Date: 2025-08-08 15:15:55.352044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e24ca79dd0e6"
down_revision: Union[str, Sequence[str], None] = "b1b3cc050712"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_index(
        op.f("chunks_embedding_idx"),
        table_name="chunks",
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.add_column(
        "generation_requests", sa.Column("user_message", sa.Text(), nullable=False)
    )
    op.add_column(
        "generation_requests", sa.Column("assistant_message", sa.Text(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generation_requests", "assistant_message")
    op.drop_column("generation_requests", "user_message")
    op.create_index(
        op.f("chunks_embedding_idx"),
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("request_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["generation_requests.id"],
            name=op.f("messages_request_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    # ### end Alembic commands ###
