"""nullable assistant message

Revision ID: fc1b561caf4d
Revises: e24ca79dd0e6
Create Date: 2025-08-08 15:24:24.797514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc1b561caf4d"
down_revision: Union[str, Sequence[str], None] = "e24ca79dd0e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "generation_requests",
        "assistant_message",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "generation_requests",
        "assistant_message",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    # ### end Alembic commands ###
