services:
    api-gateway:
        container_name: chat-api-gateway
        build:
            context: ../backend
            dockerfile: ../docker/Dockerfile.service
            args:
                SERVICE_DIR: api-gateway
        networks:
            - chat-net
        volumes:
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost/api/health']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: always
        env_file:
            - .env.prod
        depends_on:
            - kafka
            - redis
        command: uv run -m src.main

    indexation-worker:
        container_name: chat-indexation-worker
        build:
            context: ../backend
            dockerfile: ../docker/Dockerfile.service
            args:
                SERVICE_DIR: indexation_worker
        networks:
            - chat-net
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: always
        env_file:
            - .env.prod
        depends_on:
            - kafka
            - redis
        command: uv run -m indexation_consumer

    generation-worker:
        container_name: chat-generation-worker
        build:
            context: ../backend
            dockerfile: ../docker/Dockerfile.service
            args:
                SERVICE_DIR: generation_worker
        networks:
            - chat-net
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: always
        env_file:
            - .env.prod
        depends_on:
            - kafka
            - redis
        command: uv run -m generation_consumer

networks:
    chat-net:
        driver: bridge
