openai:
    model: 'gpt-4o'
    base_url: 'https://api.openai.com/v1'
    temperature: 0.7
    max_tokens: 15000
    throttle_rate_limit: 60
    throttle_period: 60.0

embeddings:
    model: 'text-embedding-3-small'
    base_url: 'https://api.openai.com/v1'
    dimensions: 1536
    throttle_rate_limit: 100
    throttle_period: 60.0

kafka:
    bootstrap_servers: 'localhost:19092'
    auto_offset_reset: 'earliest'
    enable_auto_commit: true
    max_poll_records: 100
    session_timeout_ms: 10000

    defaults:
        partitions: 3
        replication_factor: 1

    indexation:
        request:
            topic: 'tasks.indexation'
            group_id: 'indexation-workers'
        response:
            topic: 'results.indexation'
            group_id: 'indexation-result-handler'

    generation:
        request:
            topic: 'tasks.generation'
            group_id: 'generation-workers'
        response:
            topic: 'results.generation'
            group_id: 'generation-result-handler'

s3:
    service_name: 's3'
    region: 'ru-central1'
    endpoint: 'http://0.0.0.0:9000'
    pdf_bucket: 'primer-chat-pdf'
    chunks_bucket: 'primer-chat-chunks'
    presign_expire_seconds: 3600

redis:
    connection:
        host: 0.0.0.0
        port: 6379
        db: 0

    generation_buffer:
        ttl_seconds: 600

    generation_request_buffer:
        ttl_seconds: 600

    indexation_progress_buffer:
        maxlen: 2000
        ttl_seconds: 86400 # хранить сутки
        xread_block_ms:  5000
        xread_batch: 100
