[project]
name = "indexation"
version = "0.1.0"
description = "Indexation worker for Primer Chat"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.12.0",
    "asyncio>=3.4.3",
    "asyncio-throttle>=1.0.2",
    "backoff>=2.2.1",
    "bs4>=0.0.2",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "pymupdf>=1.26.3",
    "pymupdf4llm>=0.0.27",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.7.1",
    "shared-adapters",
    "shared-config",
    "shared-models",
]

[tool.uv.sources]
shared-models = { path = "../../shared-models", editable = true }
shared-adapters = { path = "../../shared-adapters", editable = true }
shared-config = { path = "../../shared-config", editable = true }
