[project]
name = "shared-config"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.6",
    "pydantic-settings>=2.2",
    "pyyaml",
    "loguru"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["shared_config"]
include-package-data = true

[tool.setuptools.package-data]
shared_config = ["*.env", "config.*.yaml"]
